### ISSUE TITLE
docker: 'network' is not a docker command. See 'docker --help'.

### ISSUE THREAD

**Issue by dragonfly-net** [turkenh/ansible-interactive-tutorial#1]
$ ./tutorial.sh 
creating network ansible.tutorial
docker: 'network' is not a docker command. See 'docker --help'.
starting container host0.example.org: mapping hostport 42726 -> container port 80 && hostport 42729 -> container port 8080
docker: --net: invalid net mode: invalid --net: ansible.tutorial. See 'docker run --help'.
Could not start host container. Exiting!

$ docker -v
Docker version 1.6.2, build 7c8fca2

$ cat /etc/lsb-release
DISTRIB_ID=LinuxMint
DISTRIB_RELEASE=17.2
DISTRIB_CODENAME=rafaela
DISTRIB_DESCRIPTION="Linux Mint 17.2 Rafaela"

**Comment by turkenh** [comment]
Your docker version seems to be too old.
`tutorial.sh` uses "docker network" command which seems to be introduced in docker 1.9.
Please update to a newer version and try again.

**Comment by dragonfly-net** [comment]
In readme:
Tested with docker versions 1.12+ but should work with other versions as well.

Please, change it to "and could't work with 1.6" or something else.
