### ISSUE TITLE
Replace state=installed with state=present

### ISSUE THREAD

**Issue by Hofer-Julian** [turkenh/ansible-interactive-tutorial#27]
First, let me thank you for your great tutorial, so far it works perfectly.

Do you think you could replace the deprecated form of the apt module `state=installed` with `state=present`?
As a beginner it confused me that `state=installed` was not present in the [documentation](https://docs.ansible.com/ansible/latest/modules/apt_module.html) and only [stackoverflow](https://stackoverflow.com/questions/39902957/what-does-state-installed-mean-in-ansible-apt) helped.

I can also make a pull request if you'd prefer that.

**Comment by turkenh** [comment]
Thanks a lot for reporting.
Fixed!
