### ISSUE TITLE
ansible-interactive-tutorial for docker 

### ISSUE THREAD

**Issue by akn416** [turkenh/ansible-interactive-tutorial#29]
I typed in "./tutorial.sh" after cloning the repository and it does not exist. Am I doing something wrong? I need help accessing the actual file.

**Comment by turkenh** [comment]
Did you get into the repository folder?

**Comment by akn416** [comment]
I think so. I cloned it successfully I believe. Am I doing something wrong?

**Comment by akn416** [comment]
![image](https://user-images.githubusercontent.com/52968393/62392296-1911c580-b535-11e9-952b-142bb4dee1db.png)

**Comment by turkenh** [comment]
You need to get into repo directory:
```
cd ansible-interactive-tutorial
```

**Comment by akn416** [comment]
alright thank you very much! Sorry about that, I am still new to github and this stuff.

**Comment by turkenh** [comment]
No problem 👍
