### ISSUE TITLE
Link to available roles in lesson 14 leads nowhere

### ISSUE THREAD

**Issue by kalvisbuls** [turkenh/ansible-interactive-tutorial#30]
As the title already states, [the link to the available roles](https://github.com/turkenh/ansible-interactive-tutorial/blob/bd0582c4e9f1292520c890ab5c62ab3c65792d18/tutorials/13-step-13.nutsh#L10) in lesson 14 results in a redirect to a "Page Not Found" (I'm guessing the URL has changed recently). I could make a pull request, but I'm not sure what the correct replacement is as I had never visited the site before.

**Comment by EarlGreyT** [comment]
https://galaxy.ansible.com/search?keywords=&order_by=-relevance&deprecated=false&type=role&page=1

this should lead you to all not deprecated roles

e: went ahead and created a pr
https://github.com/turkenh/ansible-interactive-tutorial/pull/31

**Comment by turkenh** [comment]
Closed with #31 thanks to @EarlGreyT!
