### ISSUE TITLE
tutorial.sh throws an error

### ISSUE THREAD

**Issue by mattgantner** [turkenh/ansible-interactive-tutorial#4]
I have done no debugging yet but here is the information that pertains to the event. This may not be a bug at all but rather a system setup issue on my end.

system notes:
Kernel 4.11.12-1-MANJARO
Docker version 17.10.0-ce, build f4ffd2511c

Steps to replicate:
git clone  https://github.com/turkenh/ansible-interactive-tutorial.git
cd ansible-interactive-tutorial
./tutorial.sh

output: 
./tutorial.sh 
starting container host0.example.org: mapping hostport 42726 -> container port 80 && hostport 42729 -> container port 8080
Unable to find image 'turkenh/ubuntu-1604-ansible-docker-host:1.0' locally
1.0: Pulling from turkenh/ubuntu-1604-ansible-docker-host
d5c6f90da05d: Pulling fs layer
bbbe761fcb56: Pulling fs layer
7afa5ede606f: Pulling fs layer
f6b7253b56f4: Pulling fs layer
2b8db33536d4: Pulling fs layer
a2b45d4ab2fd: Pulling fs layer
03b1c7fa7980: Pulling fs layer
10a4ee0fd8bb: Pulling fs layer
ad81eaefa5af: Pulling fs layer
751338e06da3: Pulling fs layer
f6b7253b56f4: Waiting
2b8db33536d4: Waiting
a2b45d4ab2fd: Waiting
03b1c7fa7980: Waiting
10a4ee0fd8bb: Waiting
ad81eaefa5af: Waiting
751338e06da3: Waiting
bbbe761fcb56: Verifying Checksum
bbbe761fcb56: Download complete
7afa5ede606f: Verifying Checksum
7afa5ede606f: Download complete
f6b7253b56f4: Verifying Checksum
f6b7253b56f4: Download complete
2b8db33536d4: Verifying Checksum
2b8db33536d4: Download complete
03b1c7fa7980: Download complete
10a4ee0fd8bb: Download complete
ad81eaefa5af: Download complete
751338e06da3: Verifying Checksum
751338e06da3: Download complete
d5c6f90da05d: Download complete
d5c6f90da05d: Pull complete
bbbe761fcb56: Pull complete
7afa5ede606f: Pull complete
f6b7253b56f4: Pull complete
2b8db33536d4: Pull complete
a2b45d4ab2fd: Verifying Checksum
a2b45d4ab2fd: Download complete
a2b45d4ab2fd: Pull complete
03b1c7fa7980: Pull complete
10a4ee0fd8bb: Pull complete
ad81eaefa5af: Pull complete
751338e06da3: Pull complete
Digest: sha256:84c1c22800da13f28a2a11ad3efc1d208a3c90bcd5b9687eb3ca44ebb449188f
Status: Downloaded newer image for turkenh/ubuntu-1604-ansible-docker-host:1.0
docker: Error response from daemon: oci runtime error: container_linux.go:295: starting container process caused "process_linux.go:399: container init caused \"process_linux.go:382: running prestart hook 0 caused \\\"fork/exec /usr/bin/dockerd (deleted): no such file or directory\\\"\"".
Could not start host container. Exiting!

**Comment by mattgantner** [comment]
more Docker version information
$ docker version
Client:
 Version:      17.10.0-ce
 API version:  1.32 (downgraded from 1.33)
 Go version:   go1.9.1
 Git commit:   f4ffd2511c
 Built:        Wed Oct 18 23:08:56 2017
 OS/Arch:      linux/amd64

Server:
 Version:      17.09.0-ce
 API version:  1.32 (minimum version 1.12)
 Go version:   go1.9
 Git commit:   afdb6d44a8
 Built:        Thu Oct  5 09:59:07 2017
 OS/Arch:      linux/amd64
 Experimental: false

**Comment by mattgantner** [comment]
Well, it works just fine on http://play-with-docker.com/ so the issue is related to my particular machine. If you have insight into where to start - that would be helpful!

**Comment by turkenh** [comment]
Looks like it is crashing while starting the host containers.

Can you simple try the following command:
docker run -d turkenh/ubuntu-1604-ansible-docker-host:1.0

**Comment by mattgantner** [comment]
That command worked fine. It stood up a container from the downlaoded images from my previous attempt.

**Comment by turkenh** [comment]
There are similar issue in other repositories as well: 
https://github.com/moby/moby/issues/29640
https://github.com/moby/moby/issues/22746

And a related blog post: https://www.claudiokuenzler.com/blog/689/rancher-error-response-from-daemon-dockerd-deleted-no-such-file-or-directory#.WfeOAhNL9E4

In general, a docker deamon restart is suggested to fix the issue.
Have you tried restarting your docker daemon?

**Comment by mattgantner** [comment]
Thank you for the suggestion. I'm not sure what the underlying issue was in the end but I essentially purged docker and reinstalled and now the command runs successfully. I must have had some funky setup. Thanks for your patience!

here is a version output for future reference by others in case it is meaningful. I was running API version 1.32 prior to the reinstall.

$ docker version
Client:
 Version:      17.10.0-ce
 API version:  1.33
 Go version:   go1.9.1
 Git commit:   f4ffd2511c
 Built:        Wed Oct 18 23:08:56 2017
 OS/Arch:      linux/amd64

Server:
 Version:      17.10.0-ce
 API version:  1.33 (minimum version 1.12)
 Go version:   go1.9.1
 Git commit:   f4ffd2511c
 Built:        Wed Oct 18 23:09:11 2017
 OS/Arch:      linux/amd64
 Experimental: false

**Comment by turkenh** [comment]
Closing as it is revealed as a setup issue. 
Thanks!
