### ISSUE TITLE
tutorial.sh throws an error while pulling images

### ISSUE THREAD

**Issue by benkonz** [turkenh/ansible-interactive-tutorial#8]
I am receiving an error while running the start.sh script
**system notes:**
Operating System: Windows 7 running Docker Toolbox
Docker Version: 18.01.0-ce 
Docker Machine Version: 0.13.0
**steps to reproduce**
git clone https://github.com/turkenh/ansible-interactive-tutorial.git
cd ansible-interactive-tutorial
./start.sh
![error](https://user-images.githubusercontent.com/18561476/35450623-2dc40140-0286-11e8-8ac1-b7a1fe0657c2.PNG)
![image](https://user-images.githubusercontent.com/18561476/35450894-13a0e8ae-0287-11e8-98fc-d217c9e7c2f2.png)

**Comment by turkenh** [comment]
Looks like the error is thrown by nutsh rather then docker.
I will try to reproduce on win7. 

Until then, just wanted to remind you that you can run tutorials on http://play-with-docker.com
